version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.2.0-buster
        environment:
          CXX: g++-6
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt-get -y install g++-6 lcov
            npm install
      - run:
          name: coverage
          command: npm run ci-coverage
