version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.7.0-buster
        environment:
          CXX: g++-8
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt-get -y install g++-8 lcov
            npm install
      - run:
          name: coverage
          command: npm run ci-coverage
